name: Build Only

on:
  push:
    paths:
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dist directory
        run: |
          mkdir -p dist
          if [ $? -ne 0 ]; then
            echo "Failed to create dist directory. Error code: $?"
            exit 1
          fi
          chmod -R 777 dist

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          build_output=$(npm run build 2>&1)
          echo "$build_output"
          if [ -f "dist/ha-oil-card.js" ]; then
            echo "ha-oil-card.js was generated successfully."
          else
            echo "ha-oil-card.js was not generated."
            exit 1
          fi

      - name: Package dist directory into zip
        run: zip -r ha-oil-card.zip dist

      - name: Upload build artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ha-oil-card-dist
          path: dist/ha-oil-card.zip

      - name: List dist directory after build
        run: ls -al dist
