name: Build and Release

on:
  push:
    paths:
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist && chmod -R 777 dist

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List dist directory
        run: ls -al dist

      - name: Package dist directory into zip
        run: zip -r ha-oil-card-dist.zip dist

      - name: Generate a unique release tag
        id: generate_tag
        run: |
          timestamp=$(date +%Y%m%d%H%M%S)
          tag_name="v$timestamp"
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
