name: Build and Release

on:
  push:
    paths:
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -al

      - name: Create dist directory
        run: mkdir -p dist && chmod -R 777 dist

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Print build command
        run: echo "Running build command: npm run build"

      - name: Build project
        run: npm run build

      - name: List dist directory after build
        run: ls -al dist

      - name: Package dist directory into zip
        run: zip -r ha-oil-card-dist.zip dist
