name: Build and Release

on:
  push:
    branches:
      - main  # 触发分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Package release
        run: npm run package

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oil-card-release
          path: release/

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # 仅在 main 分支触发发布
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Bump version and generate changelog
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes and tags
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push --follow-tags origin main

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/ha-oil-card-v${{ steps.bump_version.outputs.tag_name }}.zip
          asset_name: ha-oil-card-v${{ steps.bump_version.outputs.tag_name }}.zip
          asset_content_type: application/zip

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.tag_name }}
          release_name: Release ${{ steps.bump_version.outputs.tag_name }}
          body: ${{ steps.bump_version.outputs.changelog }}
          draft: false
          prerelease: false
