name: Build Only

on:
  push:
    paths:
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -al

      - name: Create dist directory
        run: mkdir -p dist && chmod -R 777 dist

      - name: Verify dist directory creation
        run: |
          if [ -d "dist" ]; then
            echo "dist directory created successfully."
          else
            echo "Failed to create dist directory."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          build_output=$(npm run build 2>&1)
          echo "$build_output"
          if [ -f "dist/ha-oil-card.js" ]; then
            echo "ha-oil-card.js was generated successfully."
          else
            echo "ha-oil-card.js was not generated."
            exit 1
          fi

      - name: List dist directory after build
        run: ls -al dist

      - name: Package dist directory into zip
        run: zip -r ha-oil-card-dist.zip dist

      - name: Verify dist directory still exists
        run: |
          if [ -d "dist" ]; then
            echo "dist directory still exists after packaging."
          else
            echo "dist directory is missing after packaging."
            exit 1
          fi

      - name: Upload build artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ha-oil-card-dist
          path: ha-oil-card-dist.zip

      - name: Check upload result
        run: |
          if [ ${{ steps.upload_artifact.outcome }} == 'success' ]; then
            echo "Artifact uploaded successfully."
          else
            echo "Artifact upload failed."
            exit 1
          fi
